name: decision-ml-env  # Nome do ambiente
channels:
  - conda-forge       # Canal comunitário para pacotes Conda
  - defaults          # Canal oficial Conda
dependencies:
  - python=3.9        # Versão do Python
  - numpy=1.21        # Versão do numpy
  - pandas=1.3        # Versão do pandas
  - scikit-learn=0.24  # Versão do scikit-learn
  - matplotlib=3.4.3   # Versão do matplotlib
  - seaborn=0.11.2    # Versão do seaborn
  - jupyterlab        # Para trabalhar com notebooks
  - pip                # Para pacotes que não estão no Conda
  - pip:
    - tensorflow       # TensorFlow para deep learning
    - fastapi          # Para criar APIs
    - uvicorn          # Servidor ASGI para o FastAPI
